# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-17 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
