# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-17 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20160717_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='access_users',
            field=models.TextField(max_length=1000),
        ),
    ]
