# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-17 10:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20160717_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='uid',
        ),
        migrations.AddField(
            model_name='image',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
